//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderList
    {
        public int ıd { get; set; }
        public string SiparisID { get; set; }
    }
}
